=== Sercos10/HTML-CSS/Trabajos Lenguaje de marcas/Trabajos XSD/examen/television.xsd
<?xml version="1.0" encoding="UTF-8" ?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="canales">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="canal" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="programacion" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="programa" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="duracion" type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="titulo" type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="descripcion" type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="clas_edad" type="xs:int" maxOccurs="unbounded"/>
                                                    <xs:element name="subtitulos" type="xs:boolean" maxOccurs="unbounded"/>
                                                    <xs:element name="idioma" maxOccurs="unbounded">
                                                        <xs:complexType>
                                                            <xs:attribute name="tipo">
                                                                <xs:simpleType>
                                                                    <xs:restriction base="xs:string">
                                                                        <xs:enumeration value="espaÃ±ol"/>
                                                                        <xs:enumeration value="ingles"/>
                                                                    </xs:restriction>
                                                                </xs:simpleType>
                                                           </xs:attribute>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="anuncio" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="marca" type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="duracion" type="xs:string" maxOccurs="unbounded"/>
                                                    <xs:element name="horario" type="xs:string" maxOccurs="unbounded"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute name="dia" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="nombre" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:maxLength value="100"></xs:maxLength>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                        <xs:attribute name="numero" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:int">
                                    <xs:pattern value="[0-9]"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sercos10/HTML-CSS/Trabajos Lenguaje de marcas/Trabajos XSD/examen/television.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE canales>
<canales xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="television.xsd">
    <canal nombre="telecinco" numero="5">
        <programacion dia="Lunes">
            <programa>
                <duracion>1,5horas</duracion>
                <titulo>Salvame Deluxe</titulo>
                <descripcion>Salen famosos que no los conocen ni en su casa discutiendo todo el rato</descripcion>
                <clas_edad>6</clas_edad>
                <subtitulos>true</subtitulos>
                <idioma tipo="español"/>
            </programa>
            <programa>
                <duracion>1 hora</duracion>
                <titulo>telediario</titulo>
                <descripcion>Simplemente te dicen las noticias del dia/semana, el 90% son malas, no merece ni la pena mirarlo</descripcion>
                <clas_edad>12</clas_edad>
                <subtitulos>true</subtitulos>
                <idioma tipo="español"/>
            </programa>
            <anuncio>
                <marca>Renault</marca>
                <duracion>30 sec</duracion>
                <horario>
                    11:30
                    15:00
                    21:45
                </horario>
            </anuncio>
            <anuncio>
                <marca>Dior</marca>
                <duracion>30 sec</duracion>
                <horario>
                    10:30
                    16:00
                    19:45
                </horario>
            </anuncio>
        </programacion>
    </canal>
</canales>
