=== Sercos10/HTML-CSS/Trabajos Lenguaje de marcas/Trabajos XSD/libro.xsd
<?xml version="1.0" encoding="UTF-8" ?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="libreria">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="libro" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="titulo" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="autor" type="xs:string" maxOccurs="unbounded"/>
                            <xs:element name="anio" type="xs:int" maxOccurs="unbounded"/>
                            <xs:element name="editora" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Sercos10/HTML-CSS/Trabajos Lenguaje de marcas/Trabajos XSD/No me acuerdo de que Ejercicios eran/libro.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria>
<libreria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="libro.xsd">
    <libro>
        <titulo>A Semantic Web Primer.</titulo>
        <autor>Antoniou, G and F. van Harmelen</autor>
        <anio>2004</anio>
        <editora>CamBridge, MA: MIT Press</editora>
    </libro>
    <libro>
        <titulo>The Semantic Web: A Guide to the Future of XMl, Web Services and Knowledge Management</titulo>
        <autor>Daconts, M.C L.J. Orgst and K.T. Smith</autor>
        <anio>2003</anio>
        <editora>New York: Wiley</editora>
    </libro>
</libreria>
